spring:
  application:
    name: BmBack
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: ${SMTP_HOST}
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${API_PORT}

app:
  scheduled:
    clean-unused-files: "0 0 3 * * ?"
  auth:
    admin-code: ${ADMIN_CODE}
    password-life-time: ${PASSWORD_LIFE_TIME}
    token:
      access-life-time: ${ACCESS_LIFE_TIME}
      refresh-life-time: ${REFRESH_LIFE_TIME}
      secret: ${SECRET}
  minio:
    username: ${MINIO_USERNAME}
    password: ${MINIO_PASSWORD}
    user-avatars-bucket: user-avatars-bucket

---
# запустить с параметром --spring.profiles.active=local
# или через переменную окружения SPRING_PROFILES_ACTIVE=local
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5444/postgres
    username: pgadmin
    password: pgadmin
    driver-class-name: org.postgresql.Driver
app:
  minio:
    endpoint: http://localhost:9003

---
# запустить с параметром --spring.profiles.active=docker
# или через переменную окружения SPRING_PROFILES_ACTIVE=docker
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://BM_POSTGRES:5432/postgres
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
app:
  minio:
    endpoint: http://minio:9000
