spring:
  application:
    name: BmBack
  datasource:
    url: jdbc:postgresql://BM_POSTGRES:5432/postgres
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

